### ISSUE TITLE
Mind adding Forgotten Circles items?

### ISSUE THREAD

**Issue by DaBomberNTG** [heisch/gloomhaven-item-db#1]
First off, thanks so much for this project, it's fantastic! Found it a couple of days ago and it's exactly what I've been looking for. Being able to search by category & text vs visuals is great. 👍 

Anyway, my party and I are about to dive into the Forgotten Circles expansion and were wondering if you had plans to add its items in. Let me know, thanks!

**Comment by heisch** [comment]
Ah forgot to watch this repo sorry for the late reply. Yes I can prob. add the forgotten circles items, but there is no eta on that.

**Comment by fifguy85** [comment]
Just a note to bump this request now that Forgotten Circles is released and the images are available on any2cards' repo.

Edit: Forgot to say again how awesome this app is and helpful in sharing the current item shop with the party (especially the inventory!). Thanks again so much!!!

**Comment by heisch** [comment]
Okay I've looked into it, I can add them but I would need some help from a volunteer.

What I need is a list of the item names and the text on the item as plain text

example: 
Ancient Bow - During your ranged attack, add +2 Attack, CURSE and WOUND to a single attack.
Basin of Prophecy - When you reveal cards from any deck, reveal one additional card.
...

I any of you can provide that I will add the items to the tool

**Comment by twmartin** [comment]
Is something like this what you are looking for?

```
Ring of Duality - After performing the top action of any ability card, you may immediately perform the bottom action of the same card. This item cannot be used if both actions would trigger a lost card icon.
Minor Antidote - The next three times you would gain POISON, prevent the condition.
Major Antidote - The next five times you would gain POISON, prevent the condition.
Curseward Armor - You are immune to CURSE, even if this item is spent. On the next three sources of damage from attacks targeting you, gain SHIELD 1.
Elemental Claymore - During your melee attack, {anyX} to add +2 Attack to a single attack.
Ancient Bow - During your ranged attack, add +2 Attack, CURSE, and WOUND to a single attack.
Rejuvenation Greaves - During your movement, add +2 Move to the movement and gain REGENERATE.
Scroll of Haste - During any one ally's movement, add +2 Move to the movement.
Cutpurse Dagger - When you kill a monster during your turn, gain one money token.
Throwing Axe - During your single-target melee attack action add Range 3 to the attack.
Rift Device - During your turn, Teleport to any unoccupied hex within 4 hexes of you.
Crystal Tiara - When you perform a long or short rest, gain STRENGTHEN.
Basin of Prophecy - When you reveal cards from any deck, reveal one additional card.
```

**Comment by heisch** [comment]
Will be solved by https://github.com/heisch/gloomhaven-item-db/pull/9

**Comment by heisch** [comment]
thanks to @solomojb forgotten circle items are now available
