### ISSUE TITLE
Settings access

### ISSUE THREAD

**Issue by solomojb** [heisch/gloomhaven-item-db#15]
@heisch Would it be possible to give me the ability to change the settings on this repo? (Or is that not allowed because it's your repo?)

I am trying to get it so that i can deploy branches so others are able to test it via Netlify.  (I don't think you can easily do this with git hub pages?)

Thanks,
Jim

**Comment by heisch** [comment]
Hmm I can only set you as collaborator. 
I could transfer the repo to you but that will break all the existing links to github.io

we could then do this: https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7

**Comment by solomojb** [comment]
That would be great. I would assume that I would first have to delete my fork? 

When you recreate the repo with just the redirect,  would it be possible for you make me a contributor to see if i can get it to redirect to netlify page.

**Comment by solomojb** [comment]
Actually thinking about it we probably want to leave it alone.  At the spoiler information is stored in the local storage and we’d have to figure out a way to transfer that over on the redirect.

I can work around it if I need to test branches remotely.

Sent from my iPhone

On Jan 27, 2021, at 4:57 AM, Nicola Heisch <notifications@github.com> wrote:

﻿

Hmm I can only set you as collaborator.
I could transfer the repo to you but that will break all the existing links to github.io

we could then do this: https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgist.github.com%2Fdomenic%2F1f286d415559b56d725bee51a62c24a7&data=04%7C01%7C%7C2f9d80dfd4224543496708d8c2a9ed75%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637473382376520804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qFOlexZz%2BzvWNCvtO%2BOQ2WDV9KSVY2IsSJyd75%2FFhqk%3D&reserved=0>

**Comment by heisch** [comment]
Could you do the Netlify tests on your fork instead?

**Comment by solomojb** [comment]
That’s what I was doing before. So I guess I could continue to do that if I need to.

Sent from my iPhone

On Jan 29, 2021, at 7:53 AM, Nicola Heisch <notifications@github.com> wrote:

﻿

Could you do the Netlify tests on your fork instead?
