### ISSUE TITLE
Wrong slot for CS item 58

### ISSUE THREAD

**Issue by emfmesquita** [heisch/gloomhaven-item-db#19]
The item 58 of Crimson Scales (gloomhaven-item-db) has body instead of small as slot.

line 2796 of https://github.com/heisch/gloomhaven-item-db/blob/master/src/games/gh/items.json

Thanks for the site, it is really useful!

**Comment by solomojb** [comment]
Thanks. I fixed and am pushing it up now.

**Comment by solomojb** [comment]
Fixed.
