### ISSUE TITLE
Solo Class Items - Music Note button does not display the item

### ISSUE THREAD

**Issue by Druaightagh** [heisch/gloomhaven-item-db#22]
Solo Class Items - Music Note button, in the Spoiler Configuration tab, is not displaying the associated item under the Item List tab.

I've attempted a combination of options/selections, but the only way I can get it to display is to disable "Respecting Spoiler Settings" (which is less than ideal).

Found on PC and Mac in latest Chrome, Edge, Firefox and Safari (on Mac), starting from scratch or via a Share link.
NB: A Share link appears to set the Music Note button as selected (red outline) but still the item doesn't appear.

PS: Thank you for providing this very useful tool :)

**Comment by solomojb** [comment]
Thanks for raising this issue.  I fixed it!
