### ISSUE TITLE
Gloomhaven: Jaws of the Lion: item #034 has wrong source

### ISSUE THREAD

**Issue by speakanton** [heisch/gloomhaven-item-db#23]
In the Gloomhaven item db for Jaws of the Lion the item #034 "Barbed Axe" the "Source" is listed as "Scenario #34".
It should be "Scenario #23".

![image](https://user-images.githubusercontent.com/192207/198826643-f07fd414-be9f-46be-832f-bb16594af8b9.png)

**Comment by solomojb** [comment]
Thanks for reporting this. Fixed it forgot to close the issue. :)
