### ISSUE TITLE
Some Data errors in FH items

### ISSUE THREAD

**Issue by Lurkars** [heisch/gloomhaven-item-db#25]
Hello, I found some small mistakes in Frosthaven Items

- **Item 15** resource `"lumber"` instead of `"metal"`
- **Item 19/20** name is in lower case!?
- **Item 41** missing resource `"metal": 1`
- **item 48** `"hide": 2` instead of `"hide": 1`
- **Item 67** missing resource `"metal": 1`
- **Item 71** missing resource `"corpsecap": 1` and `"item": [18]`

I compared with the corresponding images from Worldhaven, so I hope I didn't make mistakes myself. And I hope that this issue is okay, was to lazy to fork for PR....

**Comment by solomojb** [comment]
Thanks I’ll update these and put a new version out. 

I noticed the names of the items just hadn’t gotten around to fixing them yet. :)

**Comment by solomojb** [comment]
Fixed. If you see anything else wrong let me know!
