### ISSUE TITLE
Adding several item sources to your list

### ISSUE THREAD

**Issue by iamdrewbaker** [heisch/gloomhaven-item-db#26]
I have 74 item sources listed below, with two at the very bottom I could not find anywhere.

- **17 / Cured Hide Armor** -- Scenario 120, Treasure 50; also, Craftsman (Building 34) Level 3
- **64 / Detonator** -- Scenario 62, Treasure 21; also, Alchemist (Building 35) Level 3
- **66 / Amulet of Eternal Life** -- Scenario 188 Reward
- **68 / Scaled Armor** -- Scenario 71, Treasure 22 
- **69 / Feathered Cloak** -- Scenario 32 Reward 
- **70 / Aesther Robe** -- Scenario  81 Reward
- **71 / Bone Boots** -- Scenario13, Treasure 49 
- **72 / Oak Staff** -- Scenario 70, Treasure 82
- **73 / Energizing Baton** -- Scenario 44 Reward 
- **74 / Shock Grenades** -- Scenario 51 Reward
- **75 / Rose Gauntlet** -- Scenario 110 Reward
- **76 / Horn of Command** -- Scenario 4, Treasure 70
- **77 / Chaos Cannon** -- Scenario 15, Treasure 40
- **78 / Balanced Scales** -- Scenario 122, Treasure 31
- **79 / Roasted Fowl** -- Scenario 93 Reward 
- **80 / Living Stone** -- Scenario Scenario 63, Treasure 72
- **81 / Simulacrum** -- Scenario 68, Treasure 59
- **82 / Mechanical Cube** -- Scenario 80, _Need to open both_ Treasure 62 and Treasure 69
- **98 / Unhealthy Mixture** -- Alchemy Table; Xain's Gambit
  - __**Note:**__ _I believe Xain's Gambit is a Road Event with two outcomes: (131.1, 155.2), but that's unconfirmed at the time of this message._
- **183 / Decanter of Mists** -- Scenario 38, Treasure 16
- **193 / Mind Thieving Helmet** -- Scenario 121 Reward
- **194 / Temporal Amulet** -- Scenario 125 Reward
- **195 / Tri-Cornered Hat** -- Scenario 136, Treasure 83; and Scenario 127 Reward
-  **196 / Choker of Sacrifice** -- SR-26 (Option A)
-  **197 / Aesther Diadem** -- WO-77 (Option B)
-  **198 / Hunter's Necklace** -- WR-36 (Option B)
- **199 / Opulent Shoes** -- Scenario 80, Treasure 6; and Scenario 129, Treasure 78
- **200 / Eventide Scepter** -- Scenario 56, Treasure 4
- **201 / Wave Blade** -- Scenario 76 Reward; and Scenario 77 Reward
  - __**Note:**__ _I believe these scenarios are mutually exclusive, so this makes sense._
- **202 / Giant Piranha Pig Spine** -- Scenario 83 Reward
- **203 / Scepter of Control** -- Scenario 119 Reward
- **204 / Severed Claw** -- Scenario 49, Treasure 5; and Scenario 54, Treasure 5
  - __**Note:**__ _I believe these scenarios are mutually exclusive, so this may make sense, though unconfirmed._
- **205 / Harpoon** -- Scenario 75, Treasure 55; and Scenario 76, Treasure 55
  - __**Note:**__ _I believe these scenarios are mutually exclusive, so this may make sense, though unconfirmed._
- **206 / Giant Sword** -- Scenario 89, Treasure 42; and 183.4 Mail Call _(mail call source unknown, possibly an event?)_
- **207 / Fishhook** -- Scenario 78, Treasure 13
- **208 / Titan Nail** -- Scenario 123, Treasure 52
- **209 / Sword of Mastery** -- SR-35 (All Outcomes)
- **210 / Tanjo** -- SO-39 (Option A)
- **211 / Boom Barrel** -- B-11 (Option A)
- **212 / Elemental Stone** -- Scenario 66 Reward
- **213 / Key of Seasons** -- Scenario 106 Reward
- **214 / Cup of Ventillion** -- Scenario 107 Reward
- **215 / Befuddling Mug** -- Scenario128 Reward
- **216 / Tome of Elements** -- 104.3; and 163.1 _(Road Event outcomes, specific event unknown at this time)_
- **217 / Tome of Time** -- 107.2; and 191.1 _(Road Event outcomes, specific event unknown at this time)_
- **218 / Tome of Life** -- 81.4; and 162.5 _(Road Event outcomes, specific event unknown at this time)_
- **219 / Tome of Conflict** -- Scenario 134 Reward; and 153.3 _(Road Event outcome, specific event unknown at this time)_
- **220 / Belaras Quill** -- Scenario 135 Reward
- **221 / Ice Shiv** -- Scenario 21, Treasure 84
- **222 / Black Box** -- Scenario 27, Treasure 36
- **223 / Lightning Rod** -- Scenario 31, Treasure 26
- **225 / Algox Carving** -- Scenario 40, Treasure 41; and Scenario 55, Treasure 41
  - __**Note:**__ _I believe these scenarios are mutually exclusive, so this makes sense._
- **226 / Unfettered Arm** -- Scenario 58, Treasure 81; and WR-22 (Option A)
- **227 / Data Drive** -- Scenario 59, Treasure 7
- **228 / Extendable Pole** -- Scenario 98, Treasure 35
- **229 / Exquisite Map** -- SO-42 (Option B)
- **230 / Examination Glass** -- SR-26 (Option A)
- **231 / Skinning Knife** -- WR-16 (Option A)
- **232 / Orchid Wand** -- WR-12 (Option A)
- **233 / Dead Raven** -- Scenario 13 Reward
- **234 / Ooze Vial** -- Scenario 84 Reward
- **235 / Small Rat** -- Scenario 93 Reward
- **236 / Cracked Mirror** -- Scenario 111 Reward
- **237 / Mesmerizing Seashell** -- Scenario 131 Reward
- **238 / Cracked Idol** -- Scenario 133 Reward
- **239 / Eye of the Storm** -- Scenario 57, Treasure 53
- **240 / Demons Eye** -- 108.2 Event --> 180.2 Accuse Cecil Event Reward (Specific event unknown at this time)
- **241 / Shimmering Powder** -- SR-26 (Option A)
- **242 / Lucky Dice** -- SO-04 (Option C, which is an unknown option)
- **243 / Cursed Rock** -- WR-03 (Option A)
- **244 / Ember Energy Source** -- Scenario 33 Reward
- **245 / Ancient Coin** -- Scenario 136 Reward; Tavern (Building 74) Upgraded to Level 3, 128.5 on Loot Card 1419; 133.4 on Loot Card 1418
- **246 / Key Card** -- Scenario 58 Reward; and Scenario 59 Reward
  - __**Note:**__ _I believe these scenarios are mutually exclusive._
- **247 / Trainer's Net** -- Stables (Building 88) Built

_EDIT: Added multiple road and outpost event related items._

_UNKNOWN: 67 - Converging Lenses; and 224 - Armor of Empathy._

**Comment by solomojb** [comment]
Awesome!!!  Thanks for this. 

Do you have the Envelope/Building numbers for Tavern and Stables? (I would prefer to put those in instead of the name of the building to protect spoilers)

For the ones Labeled things like: "Scenario 59, Treasure 7" is it Either "Treasure 7 which comes from Scenario 59" or "Scenario 59 OR Treasure 7".  (I'd be inclined if it's the former to just say "Treasure 7")

I am going to put the section numbers for now, and if you find more specific details down the road, we can update the list.

**Comment by iamdrewbaker** [comment]
- Tavern is 74; Stables is 88.
- "Scenario x, Treasure y" would mean, the treasure y, which is located within scenario x, so just listing the Treasure number is sufficient if that's all you want to list.

I'll check back here in a few hours once I am home from work and can review my notes I have. There are a bunch more that are from events, so I don't have that info accessible at the moment.

**Comment by solomojb** [comment]
No worries. When you can. I'll (hopefully) have time later today to add the details.

**Comment by iamdrewbaker** [comment]
Updated the original list with the remaining notes I have on those items.

**Comment by solomojb** [comment]
Thanks again!

**Comment by solomojb** [comment]
Item 211 what’s “b-11”?

**Comment by iamdrewbaker** [comment]
Similar to SR... Summer Road, B stands for Boat, there are Boat Events once that feature is unlocked.

**Comment by solomojb** [comment]
Oh I didn’t know that! Cool.

**Comment by iamdrewbaker** [comment]
Since we're beyond spoilers at this point, the Boat Events are envelope B.

**Comment by solomojb** [comment]
Ok. Should it be listed as envelope b or boat event? 

Trying to figure out how best to keep things spoiled?

**Comment by iamdrewbaker** [comment]
Well, to get the Boat Events, envelope B would need to be unlocked; but the item is specifically Boat Event 11. Your call how you want to label it. [Boat Event 11 Back](https://github.com/any2cards/frosthaven/blob/master/images/events/frosthaven/boat/fh-be-11-b.png)

**Comment by solomojb** [comment]
I found where Xain's Gabits comes from: WO-10
Tracking down some of the other events as well.

**Comment by solomojb** [comment]
The other events: (In case you want to update your list)
```
81.4
162.5
	142.1
		?

104.3
163.1
	44.4
		?

107.2
191.1
	181.1
		?

153.3
	?

183.4 - SO-30


// These two are intertwinned some how
180.2
	88.2
		108.2
			113.2
			117.1
				144.2
					?
				187.3
					?
		113.2
		117.1
			144.2
				?
			187.3
				?
		135.5
			113.2
			117.1
				above
		149.2
			108.2
				above
			135.5
				above
			150.1
				below
			172.4
				below
			185.3
				below
		150.1
			113.2
			117.1
				above
		166.1
			108.2
				above
			135.5
				above
			150.1
				above
			172.4
				below
			185.3
				below	
		172.4
			113.2
			117.1
				above
		179.3
			108.2
				above
			135.5
				above
			150.1
				above
			172.4
				above
			185.3
				below
		185.3
			113.2
			117.1
				above

44.4 -> SR-48 Event chain, WR-46 event chain
142.1 -> SR-47 Event Chain, WR-45 event chain
153.3 -> Scenario 134
181.1 -> SR-49 event chain, WR-47 event chain

144.2 -> SO-53 event chain
187.3 -> SO-53 event chain

```

**Comment by solomojb** [comment]
I pushed out all these updates to the website.
