### ISSUE TITLE
FH item #54 labeled as a Head slot item.

### ISSUE THREAD

**Issue by DaBomberNTG** [heisch/gloomhaven-item-db#27]
![image](https://user-images.githubusercontent.com/5866651/226995526-d5304139-a3b7-4a47-bd78-ed42421e8e67.png)

**Comment by solomojb** [comment]
Thanks for pointing this out. I found a few more that were labelled incorrectly. I'll be publishing a fix for this soon.

**Comment by solomojb** [comment]
This has been fixed and is live on the website.
