### ISSUE TITLE
[Feature Request] Add selected Game to Shared Url

### ISSUE THREAD

**Issue by pikdonker** [heisch/gloomhaven-item-db#28]
Hey, Thanks for this amazing resource! 

To make it a little more usable for our Frosthaven campaign, would it be possible to save the selected game in the share url? 

That way you'd see the Frosthaven items directly when accessing a shared Frosthaven url, instead of having to select it manually. This doesn't seem to be working right now.

**Comment by solomojb** [comment]
Question about this:  When you give someone the share link, does it not retain the game they are on?  They should just have to choose it one time and only switch if you want to see the data from other games.

The share link provides data for all three games.  I think it would be confusing for a user to always jump to the game the exporter was looking at.

**Comment by pikdonker** [comment]
Wouldn't it be rare to play different games at the same time? I'd say a link with the game included would be quite logical.. But that's just me.. 

Our experience is that switching to the correct game is necessary more often than you'd like due to using different browsers/machines/private browsing (at work..), so a link with the selected game included would save some clicks/some confusion..

**Comment by solomojb** [comment]
I have added this feature to the share ability.  Please try it out on the latest version and let me know what you think. 

I have been working on a new sharing mode. If you go to https://heisch.github.io/gloomhaven-item-db/?sharing=true you can experiment with a new form of sharing. (Via an account where you don't need to give a new url each time) I would love feedback on it.

You need to log in either via google. or email then you share with a different link. Only you need to log in, the people you share with do not have to sign in.

**Comment by pikdonker** [comment]
> I have added this feature to the share ability. Please try it out on the latest version and let me know what you think.

Thanks! This seems to work great, so I'm closing this issue.

> I have been working on a new sharing mode. If you go to https://heisch.github.io/gloomhaven-item-db/?sharing=true you can experiment with a new form of sharing. (Via an account where you don't need to give a new url each time) I would love feedback on it.
> 
> You need to log in either via google. or email then you share with a different link. Only you need to log in, the people you share with do not have to sign in.

Will try that later, hopefully next week. Don't have much time this week..
