### ISSUE TITLE
Frosthaven Item 167 wrongly catagorised

### ISSUE THREAD

**Issue by Shandyan** [heisch/gloomhaven-item-db#32]
Item 167 is from the random loot deck, and not envelope 39.

**Comment by solomojb** [comment]
It is not. if you look at the Building 39, level 3 it says to add cards 164 to 167 to  the item deck.

**Comment by Shandyan** [comment]
How odd! Item 167 is from the purple-backed loot deck - which is how I got it, as we haven't unlocked building 39 yet.

**Comment by solomojb** [comment]
Are you sure you set up the game correctly? Looking at the setup guide it clearly states that items 129-167 are purchasable, and that 168-192 are random.

**Comment by Shandyan** [comment]
Item 167 is also unlocked by event wr-10. It's not a random item though, so apologies for the confusion there.
