### ISSUE TITLE
FH #015 - is only available once, but there are 2 in the game.

### ISSUE THREAD

**Issue by skahunter** [heisch/gloomhaven-item-db#37]

**Comment by skahunter** [comment]
heisch/gloomhaven-item-db/src/games/fh/items.json#220 increase count:1 to count:2

**Comment by solomojb** [comment]
Are you sure on this? Looking at the item it says 1/1

**Comment by scottmk** [comment]
The image you have uploaded even says 1/2, but here's a picture of the second card:

<img src="https://github.com/heisch/gloomhaven-item-db/assets/3020184/a34503a7-50e6-4c48-8501-f644c416c5a4" alt="PXL_20240112_175155566 MP~2" width="200"/>

**Comment by solomojb** [comment]
Yeah... i am not too sure what i item i was looking at. Next time i am in the code, i'll make the change.

Thanks for pointing that out!

**Comment by japipoju** [comment]
![image](https://github.com/heisch/gloomhaven-item-db/assets/10128839/559f1c5a-5da5-4fc6-b108-b64546e650da)
Horned Helm, FH#139 has the same problem. If you could add this to the same PR, thanks!

**Comment by solomojb** [comment]
Finally getting around to fixing this. thanks!
