### ISSUE TITLE
Visiting share link triggers endless "cycle" of imports; breaking it doesn't yield the expected configuration

### ISSUE THREAD

**Issue by benknoble** [heisch/gloomhaven-item-db#38]
The link in question is https://heisch.github.io/gloomhaven-item-db/?importFrom=DJsksfShPWRIhBWaE4hNI7FqZ7A2&lastGame=fh, which I generated using my account. (If I look at the page now and click Export I get a slightly different link https://heisch.github.io/gloomhaven-item-db/?importFrom=DJsksfShPWRIhBWaE4hNI7FqZ7A2&lastGame=null but with the same problems.)

I was really hoping the account system would mean I don't have to generate a new link after each session, but it seems to not be working right now?

**Comment by solomojb** [comment]
That's really odd.   I clicked your link got asked once then it stopped. (I am assuming by cycle you mean it constantly asks you to import?)

It should behave as you expected with only one link. I just signed it with my account as well, and I didn't see anything a cycle of imports.  

And does it happen in incognito mode?

**Comment by benknoble** [comment]
Using an incognito Chrome window or a private Safari window, I do not get the import cycle. I do have the following problems:
- `lastGame=null` is definitely wrong and should be `lastGame=fh`. Changing it manually works, but:
- Stock management doesn't load (loads as "None"; should be "Simple")
- Included Games doesn't load (none checked; should be "FH solo", "GH"
- Because of that, solo and Imported items also don't load.

I can try to "reload" the page (bypassing cache, etc.) to see if that helps the import cycle, but it seems the exported data isn't quite right, either.

**Comment by benknoble** [comment]
In fact, it seems my open page was corrupted by one of my attempts, so I've got to reset the stock management and games manually. Fortunately, I think I know what changes to make :(

**Comment by solomojb** [comment]
I was looking at your config, and as you made a change and exported, i was able to see the changes locally.

**Comment by solomojb** [comment]
The new data does seem to persist now as i just loaded it again in incognito.

**Comment by solomojb** [comment]
I did just notice a bug... if you have the share screen open and then change the game using the pulldown, it doesn't fully update the name properly. I wonder if you some how got into a state and it pull null on the end causing the data to corrupt. 

(I'll have to look at this when i got time. ;))

**Comment by benknoble** [comment]
Since it seems to be working now, I'll close this (good ol' rubber duck). But it sounds like you uncovered a real bug that you might want to track :)
