### ISSUE TITLE
Items unlocked from TP3 - #120 Staff of Summoning tickbox not shown

### ISSUE THREAD

**Issue by DaveDanger1** [heisch/gloomhaven-item-db#39]
Hi, we built Trading Post level 3, and as per section 38.3 are importing the items previously unlocked in Gloomhaven.  However, item 120 isn't in the list of unlockables on the spoiler configuration tab.  Can it be fixed, or is the entry in the section book in error?

**Comment by solomojb** [comment]
Nice catch, just an omission on my part. Fixed.
