### ISSUE TITLE
Add Gloomhaven items 21, 37, 53, 93, 94, 106, 115 to Frosthaven config

### ISSUE THREAD

**Issue by crfrolik** [heisch/gloomhaven-item-db#41]
From section 12.4:

![image](https://github.com/user-attachments/assets/b95941c5-bcfd-45ce-862f-82fbaaf7c560)

**Comment by solomojb** [comment]
What's not working with this? If i unlock the Appropriate building and level (trying to maintain spoilers here) and have GH checked in the list of games, the items show up at the bottom of the config page for you to add.

**Comment by crfrolik** [comment]
Thanks, I see it now.
I've been ignoring (or possibly just missed) the envelope unlock options.

**Comment by solomojb** [comment]
No worries.  I didn't want to assume that any of them were automatically unlocked and check them by default. ;)
