### ISSUE TITLE
Not really an issue more of a question

### ISSUE THREAD

**Issue by solomojb** [heisch/gloomhaven-item-db#6]
Hello!

 First huge thank you! I love the site and have been using it with my friends now for a bit.

 I had downloaded the code as i wanted to add a feature to it (Assuming it would be ok... as you'd have to approve the PR)

 The feature is to add a party tab so you can toggle which characters are in your group. Then i was thinking i would allow on the inventory screen to be able to mark which character possessed which item.  Further i was going to add filtering by a character.  There have been times where i have been coordinating with a friend to say "Ok i think you have these items... but i think i am missing one... tell me what you think you have?"

  What do you think of this?

  The second reason i was writing, as i was in the process of writing the addition, and i hard time accessing the state the way i was doing it, (I had the new tab as a separate component, and i was trying to link the state but it wasn't working)

  I actually made a branch, and rewrote the state using redux. (Reducers, actions and the like)  I didn't refactor TOO much to do this, but (as i figured) when i went to push i got a permissions error.

  So... the second question... do you want to see this changes?  Is this something you'd want to add to your project? (It might help adding new things into the state in the future should you decide to break up the project from the one monolithic view... like i was trying to do)  

Again,  thanks for writing this app... if anything i got to learn a little more about state/reducers and the such in a fun way in a project i like!

Jim

**Comment by heisch** [comment]
Hey Jim

Glad you like my little project.
I have to admit that from my point this is more or less abandoned now since I haven't played Gloomhaven in a Year or so.
So I'm glad when guys like you pick it up and try to enhance it.
For the permission Error: did you try to push to my repository? If yes that doesn't work. You need to fork the repository to have a copy under your account and then you can make a PR against the original repository which I then can approve.

**Comment by solomojb** [comment]
Hey again

  I forgot about forking. I created one last night and pushed to it.

  Would you be ok if I continued to refactor and enhance it then? I was thinking I could add forgotten circles to it as well.

  If others are benefitting from it, I would be more than happy to continue to improve it. I’d hate to continue to bother you though to do PR and merges. :)

Jim

Sent from my iPhone

On Jul 6, 2020, at 3:25 AM, Nicola Heisch <notifications@github.com> wrote:

﻿

Hey Jim

Glad you like my little project.
I have to admit that from my point this is more or less abandoned now since I haven't played Gloomhaven in a Year or so.
So I'm glad when guys like you pick it up and try to enhance it.
For the permission Error: did you try to push to my repository? If yes that doesn't work. You need to fork the repository to have a copy under your account and then you can make a PR against the original repository which I then can approve.

**Comment by heisch** [comment]
Absolutely, this is one of the reasons why I made the repository open for everyone 😃

**Comment by nicholaskillin** [comment]
@solomojb thanks for picking this up and improving it. I’m the person that created the Gloomhaven Battle Goals Bot, which uses this project to distribute battle goals quickly and secretly to players through Discord. 

I’ve been working on some React apps and plan to continue keeping the Discord Bot updated. 

If you are open to it I’d love to watch as the project grows and maybe even contribute to it if I can. Just let me know if I can assist in any way.

**Comment by solomojb** [comment]
Hi Nick

  Absolutely! I love collaborating with other people on code.

  Going to create a PR in a bit  for the first set of changes.

Jim

Sent from my iPhone

On Jul 6, 2020, at 11:28 AM, Nick Killin <notifications@github.com> wrote:

﻿

@solomojb<https://github.com/solomojb> thanks for picking this up and improving it. I’m the person that created the Gloomhaven Battle Goals Bot, which uses this project to distribute battle goals quickly and secretly to players through Discord.

I’ve been working on some React apps and plan to continue keeping the Discord Bot updated.

If you are open to it I’d love to watch as the project grows and maybe even contribute to it if I can. Just let me know if I can assist in any way.
